### ISSUE TITLE
Chyba v programu

### ISSUE THREAD

**Issue by DominikZampach** [Farman52/desetiprsty#1]
Vyhodnocení programu Deseti prsty mi dává mé jméno do hranatých závorek (viz. obrázek 1), ale tvůj program tuto věc nedělá (viz. obrázek 2)
![Lekce32_2chyby(za1)](https://user-images.githubusercontent.com/86419582/211344259-9cd57487-ddd6-41fd-84e3-173d76fc6f3c.png)
![image](https://user-images.githubusercontent.com/86419582/211344312-ed16451c-aa39-4784-b7b8-7f5e435d8e22.png)

**Comment by Farman52** [comment]
Hranaté závorky je potřeba připsat k dotazovanému jménu, v oficiálním programu DesetiPrsty to je tak, že by se v Informace o uživateli mělo nacházet "<jméno> <příjmení> [<přezdívka>]"
